name: Deploying
on:
 push:
   branches: [main]

jobs:
  Deploy:
   name: Deploy file into nginx
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: install nginx into ec2 machine and deploy file
      env:
       PRIVATE_KEY : ${{ secrets.SSH_PRIVATE_KEY }}

      run: |
       echo "$PRIVATE_KEY" > privkey.pem && chmod 600 privkey.pem
       
       echo "copyiing local file into ec2 machine"
       scp -o StrictHostKeyChecking=no -i privkey.pem index.html ec2-user@ec2-3-8-122-121.eu-west-2.compute.amazonaws.com:~/
       
       
       echo "conneting to ec2 via ssh & installing nginx"
       ssh -o StrictHostKeyChecking=no -i privkey.pem ec2-user@ec2-3-8-122-121.eu-west-2.compute.amazonaws.com '
       sudo yum install nginx -y
       sudo service nginx start
       sudo mv ~/index.html /usr/share/nginx/html
       '
