name: Deploying
on:
 push:
   branches: [push]

jobs:
  Deploy:
   name: Deploy file into nginx
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: install nginx into ec2 machine and deploy file
      env:
       PRIAVTE-KEY : ${{ secrets. SSH_PRIVATE}_KEY }}

      run: |
       echo "copying local file into ec2 machine"
       scp -o StrictHostKeyChecking=no -i privkey.pem index.html ec2-user@ec2-3-8-122-121.eu-west-2.compute.amazonaws.com:~/
       echo "transferring key to a file and giving secrured permissions"
       echo "$PRIVATE_KEY" > privkey.pem && chmod 600 privkey.pem
       echo " conneting to ec2 via ssh"
       ssh -o StrictHostKeyChecking=no -i privkey.pem ec2-user@ec2-3-8-122-121.eu-west-2.compute.amazonaws.com '
       sudo yum install nginx -y
       sudo service niginx start
       '